#!/bin/bash
module load gnuplot

# Use the file already generated by matdyn.x
INPUT_GP="MoS2.freq.gp"
SVG_OUT="ars_matdyn_check.svg"

COLS=$(head -n 1 $INPUT_GP | wc -w)

echo "Plotting $INPUT_GP with $COLS columns..."

gnuplot -p << EOF
    set terminal svg size 800,600 background "white"
    set output "$SVG_OUT"
    set title "MoS2 Phonon Dispersion"
    set ylabel "Frequency (cm^{-1})"
    set xlabel "Wavevector"
    set grid
    # Plot columns 2 through the end (column 1 is the x-axis)
    plot for [i=2:$COLS] "$INPUT_GP" u 1:i w l lw 2 notitle
    
    set terminal x11
    replot
EOF

echo "Done. Created $SVG_OUT"
